Add function to load PREM
fatiando/rockhound pull request #10
Opened 2018-11-07 21:35 UTC by santis19

Add function to load PREM data into `pandas.DataFrame`.
Add tests for the new function, entry in the documentation and a gallery example.

Fixes #8 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

2018-11-07 21:52 UTC, santis19 commented
@leouieda 
I have a few questions:
* Should we add `pandas` as dependency?
* Once the documentation is build, the `pandas.DataFrame` has no link, how can we solve it?
* `pylint` raises an error with the `:math:\eta` string in the docstring of `fetch_prem()` function. I don't know why this would be an error.

2018-11-07 21:57 UTC, leouieda requested changes
> Should we add pandas as dependency?

Yes please. Add it to `requirements.txt`, `setup.py`, `doc/install.rst` and `environment.yml`.

> Once the documentation is build, the pandas.DataFrame has no link, how can we solve it?

That's done by intersphinx. You'll need to add this line: https://github.com/fatiando/harmonica/blob/master/doc/conf.py#L34

2018-11-07 21:57 UTC, leouieda commented on rockhound/prem.py
> +        The loaded data or the file path ot the downloaded data.
Could you please add the names and units of the columns in the DataFrame?

2018-11-07 21:57 UTC, leouieda commented on rockhound/prem.py
> +    Fetch the Preliminary Reference Earth Model (PREM) model.
```suggestion
    Fetch the Preliminary Reference Earth Model (PREM).
```

2018-11-07 21:57 UTC, leouieda commented on rockhound/prem.py
> +    """
```suggestion
    r"""
```

You need to make this a raw string in order to have `\` in there. I think that's what pylint is complaining about.

2018-11-08 17:59 UTC, santis19 commented
@leouieda 
I've added `pandas` as dependency, fixed the `r"""` issue and added columns a units name in `prem` `DataFrame`.

I've also fixed some issues regarding styling.
If you agree, this PR is ready to merge.

2018-11-08 20:25 UTC, leouieda approved these changes

2018-11-08 20:26 UTC, merged

2018-11-08 20:26 UTC, leouieda commented
:+1: thanks, Santi!